language: go
go:
  - 1.9.3

sudo: required

script:
  - go get -t ./...
  - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -v -o spammer-linux-amd64
  - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -v -o spammer-linux-arm64
  - GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -v -o spammer-win64.exe
  - GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -v -o spammer-darwin64
  - ls

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - spammer-linux-amd64
    - spammer-linux-arm64
    - spammer-win64.exe
    - spammer-darwin64
  skip_cleanup: true
  on:
    tags: true