language: go
go:
  - 1.10rc1

script:
  - go get -t ./...
  - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -v -o spammer-$TRAVIS_TAG-linux-amd64
  - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -v -o spammer-$TRAVIS_TAG-linux-arm64
  - GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -v -o spammer-$TRAVIS_TAG-darwin64
  - GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -v -o spammer-$TRAVIS_TAG-win64.exe
  - chmod 770 spammer-linux-amd64
  - chmod 770 spammer-linux-arm64
  - chmod 770 spammer-darwin64
  - ls
  on:
    tags: true

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - spammer-linux-amd64
    - spammer-linux-arm64
    - spammer-win64.exe
    - spammer-darwin64
  skip_cleanup: true
  on:
    tags: true